# These are supported funding model platforms
# Flixty — Funding / Sponsorship
# GitHub will display a "Sponsor" button linking to these

# GitHub Sponsors
github: nexusrun

# Ko-fi
ko_fi: saifali39166

# Patreon
# patreon: yourpatreon

# Open Collective
# open_collective: flixty

# Custom URLs (up to 4)
custom:
  - https://nexusai.run
